# -*- coding: utf-8 -*-
"""buildwithai_sample.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZzcL1ouE_NE-XQGhHk7dnaIDZoucS9Oe
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd

import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import folium
from folium import plugins

plt.rcParams['figure.figsize'] = 10,12

import warnings
warnings.filterwarnings('ignore')



"""**Part 1 : Analyzing the present Condition in USA**

**How it started in USA?**

On 20 january,the first known case of COVID-19 was confirmed in the Pacific Northwest state of Washington in a man who had returned from Wuhan on 15 january.Then,the first death happend in february.By the end of March,cases had occurred in all 50 US states.As of June 24 2020,U.S had the most confirmed active cases and deaths in the world.In july 24,2020, USA becomes the eleventh-highest deathrate globally.

Even there is an exponential growth in this pandemic,eventually the growth slows down and flatterns the curve and we end up with a sigmoid

**Part 1.1 Reading Datasets**
"""

df = pd.read_excel('/content/USA_book.xlsx')
df_USA = df.copy()
df

USA_coord = pd.read_excel('/content/coordinates.xlsx')

"""**1.2 Analysing COVID19 Cases in USA**"""

df.style.background_gradient(cmap='Reds')



"""**Visualization Inference:**

On the date of '2020-07-25' ,

1.   Total_cases = 4112529.000000
2.   New_cases = 78427.000000
3.   Total deaths = 145546.000000
4.   New_Deaths = 1304.000000

When data have been analized by color downwards,up to certain row , there is no color indication.But after certain point, color starts to convert from none to extremly dark red in the speed of exponential rate.

**1.3 Active Covid Cases**
"""

df['Total Active'] = df['total_cases'] - df['total_deaths']
Tot_Cases = df.groupby('date')['Total Active'].sum().sort_values(ascending=False).to_frame()
Tot_Cases.style.background_gradient(cmap='Reds')

"""**Visual inference**

Above visual representation shows the data inlcuding virgin islands and other 50 states.And , total active cases gained by only total deaths and total cases.(not total cured).According to above data,there is an exponential growth in total active cases by time.

**1.4 How the coronavirus cases are rising?**
"""

import plotly
plotly.io.renderers.default = 'colab'

dbd_USA = pd.read_excel('/content/USA-only.xlsx', parse_dates=True)

fig = go.Figure()
fig.add_trace(go.Scatter(x=dbd_USA['date'], y = dbd_USA['total_cases'], mode ='lines+markers', name='total_cases'))
fig.update_layout(title_text='Trend of CoronaVirus Cases in USA(Cumaltive cases)',plot_bgcolor='rgb(230, 230, 230)')
fig.show()

import plotly.express as px

fig = px.bar(dbd_USA, x = "date", y = "new_cases", barmode = 'group', height=400)
fig.update_layout(title_text = 'Coronavirus new cases in usa daily basis ', plot_bgcolor='rgb(230, 230, 230)')

fig.show()

fig = px.bar(dbd_USA, x = "date", y = "total_deaths", barmode = 'group', height=400)
fig.update_layout(title_text = 'Coronavirus total_deaths in usa daily basis ', plot_bgcolor='rgb(240, 240, 240)')

fig.show()

fig = px.bar(dbd_USA, x = "date", y = "new_deaths", barmode = 'group', height=400)
fig.update_layout(title_text = 'Coronavirus new_deaths in usa daily basis ', plot_bgcolor='rgb(230, 230, 230)')

fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter(x=dbd_USA['date'], y = dbd_USA['stringency_index'], mode ='lines+markers', name='total_cases'))
fig.update_layout(title_text='stringency_index in USA(Cumaltive cases)',plot_bgcolor='rgb(230, 230, 230)')
fig.show()

fig = px.bar(dbd_USA, x = "date", y = "total_tests", barmode = 'group', height=400)
fig.update_layout(title_text = 'Coronavirus total tests in usa daily basis ', plot_bgcolor='rgb(230, 230, 230)')

fig.show()

fig = px.bar(dbd_USA, x = "date", y = "new_tests", barmode = 'group', height=400)
fig.update_layout(title_text = 'Coronavirus new tests in usa daily basis ', plot_bgcolor='rgb(230, 230, 230)')

fig.show()

"""**Visual inference**

***Why United States can't control the pandemice even they have the highest testing per daily basis and incrementing daily testing rate?***

**USA in the stage 4 which means disease takes shape of an epidemic with no clear endpoint.Official assumption is that after  the first occurance of covid19 case,state of no quick response or no testing lead usa to today's threaten situation.Even though USA have the most PCR testing per daily basis,country can't control the pandemic due to some root factors.Those root factors affects the prediction of situation in 27 july to 15 august.**
"""

from fbprophet import Prophet

confirmed = df.groupby('date').sum()['total_cases'].reset_index()
deaths = df.groupby('date').sum()['total_deaths'].reset_index()

confirmed.columns = ['ds','y']
confirmed['ds'] =pd.to_datetime(confirmed['ds'])

confirmed.tail()

"""**2.Forecasting Confirmed cases with prophet**"""

m = Prophet(interval_width=0.95)
m.fit(confirmed)
future = m.make_future_dataframe(periods=7)
future.tail()

forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()

confirmed_forecast_plot = m.plot(forecast)

confirmed_forecast_plot = m.plot_components(forecast)

"""**3.Forecasting death cases with prophet**"""

deaths.columns = ['ds', 'y']
deaths['ds'] = pd.to_datetime(deaths['ds'])

m = Prophet(interval_width=0.95)
m.fit(deaths)
future = m.make_future_dataframe(periods=7)
future.tail()

forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()

deaths_forecast_plot = m.plot(forecast)

deaths_forecast_plot = m.plot_components(forecast)

"""**Conclusion**"""